### ISSUE TITLE
Populate pages with 2018 candidate info

### ISSUE THREAD

**Issue by KristinaTaylor** [CivicTechWR/WRvotes#13]
The links to current 2018 candidates for local municipalities can be found in the wiki here: https://github.com/CivicTechWR/WRvotes/wiki/2018-Candidate-Listing-Pages

I set up a possible site structure (other ideas are welcome) where per-ward candidate info could be structured under `municipality/ward_number` like https://github.com/CivicTechWR/WRvotes/tree/master/docs/waterloo/7

We won't be able to fully populate these until nominations close in July, but it's worth sorting out structure for the content we want to share, early.

**Comment by jeffwoods** [comment]
Kejo is going to ask the city about the process around updating the city sites and the open data site with the candidate info.

@ToddTurnbull has written an initial scraper to get this data from a single city site, which could be extended to other cities, if that is the richest, most maintained version of the data.  If the open data portal is the most well maintained, it is a better candidate to use as an input for this process.

**Comment by pnijjar** [comment]
Instead of having a deeply nested site structure, I am putting all ward pages under `wards`. There are currently not separate pages for each race. I may create a secret page (not linked in the main menu) to list every race and every nominee for that race on a single page. 

It is possible that we want to hide irrelevant races (eg for the school board). I expect Javascript will be involved.

**Comment by KristinaTaylor** [comment]
Nominations have closed & the published data is fully populated at this point, but I'm leaving this open (and assigned to myself) while I hunt down twitter handles and finish QAing the data we have.

**Comment by pnijjar** [comment]
There are still many errors with the data. Kelly Galloway-Sealock is Kitchener Ward 5, but listed as Kitchener Ward 4, for example. I will fix what I see, but we need a bunch more QA on this.

**Comment by KristinaTaylor** [comment]
I think the work by Hayley covers the second/third set of eyes - it will be ongoing to update as we get more feedback from candidates.
