### ISSUE TITLE
How should people contact the site?

### ISSUE THREAD

**Issue by pnijjar** [CivicTechWR/WRvotes#23]
The civictechwr.org site lists an email using some magic I don't quite understand (it uses a my-email tag which I guess dissuades spammers). That might work for waterlooregionvotes too, but I do not know how it is implemented. 

Another issue: should one person be getting these emails or should it be a group of people? Is there a way to set up a group alias?

I was also looking how to set up a contact form on Jekyll on Github pages. It looks like this requires a third party service to be a backend. Is there a way around this?

**Comment by pnijjar** [comment]
I can offer two options, neither of which is ideal: 
- I can create a Mailman mailing list under the domain off-topic.kwlug.org . So we could have a mailing list that is something like "waterlooregionvotes@off-topic..."
- I can set up an alias that can send mail directly to a bunch of people, also under off-topic.kwlug.org . I can forward as many addresses as you want this way, but I need to know what those addresses are. 

I guess I could also make a different subdomain off of kwlug.org, such as civictechwr.kwlug.org . That is a little more work. If you can set DNS records on civictechwr.org or waterlooregionvotes.org then we could probably make a subdomain on the same CPanel that kwlug.org uses. I think I have done this before but I do not remember the steps. 

off-topic.kwlug.org is donated space and (in principle) could disappear at any time, but I expect it will continue to exist until October 23. 

Can you make multiple aliases under waterlooregionvotes.org ? Or is it on the same provider?

**Comment by KristinaTaylor** [comment]
I just set up a civictechwr.wrvotes@gmail.com and we can set it up either so other people can access the inbox as delegates (if they have an @gmail.com address) or I can set up forwards from within that account - I sent you an invite for a delegate, but if you'd prefer a forward, let me know.

**Comment by pnijjar** [comment]
Forward, please. I have a Gmail account but avoid using it as much as possible. You can forward to my yahoo account.

**Comment by KristinaTaylor** [comment]
This is settled for now - contact me or @pnijjar if you're willing & available to respond to incoming messages.
