### ISSUE TITLE
www.waterlooregionvotes.org does not resolve

### ISSUE THREAD

**Issue by pnijjar** [CivicTechWR/WRvotes#29]
http://waterlooregionvotes.org does resolve. http://www.waterlooregionvotes.org does not. I am guessing that there is either configuration with the DNS or in the CNAME file that needs to be changed, but I am not going to investigate today.

**Comment by KristinaTaylor** [comment]
@jeffwoods would you be able to help with this?

**Comment by KristinaTaylor** [comment]
Jeff fixed this.

**Comment by pnijjar** [comment]
Reopening.

The domain now resolves but https is broken (you get security certificate warnings on https://www.waterlooregionvotes.org ). 

Apparently you may need to remove and then re-add the custom domain for https to be enabled? See https://help.github.com/articles/troubleshooting-custom-domains/#https-errors . Again, this requires twiddling with the settings of the project.

**Comment by pnijjar** [comment]
I went mad with power and changed the settings in the custom domain. This seemed to regenerate certificates. I am not getting certificate errors on www.waterlooregionvotes.org any more, so I am marking this as fixed.

It looks like Github will redirect pages to a canonical url, which is waterlooregionvotes.org, not www.waterlooregionvotes.org . I am happy with this, but if you are not you can change it so that www is canonical.
