### ISSUE TITLE
Website should enforce https

### ISSUE THREAD

**Issue by pnijjar** [CivicTechWR/WRvotes#30]
Websites of the form foo.github.io automatically use https. There seems to be some confusion as to whether third party domain names can use this, but I think this is resolved. It even appears that we are being encrypted! However, we are not enforcing encryption, so that needs to happen. 

See: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

Also: https://help.github.com/articles/securing-your-github-pages-site-with-https/

I do not see a settings button, so maybe I am blind or maybe I do not have sufficient rights to change this setting.

**Comment by KristinaTaylor** [comment]
I think I found the setting and enforced it. Let me know if it's not doing what you're expecting.
