### ISSUE TITLE
Events CSV should be imported into Google Calendar

### ISSUE THREAD

**Issue by pnijjar** [CivicTechWR/WRvotes#39]
It does not need to be Google Calendar, but it should be something that can display events in a calendar format. @slin1202 has volunteered to take this on. 

For Sean: the code I wrote to pull events from Google Calendars is here: https://github.com/pnijjar/google-calendar-helpers . 

You will also want to send your GMail address to civictechwr@gmail.com so that Kristina can give you write access to the calendar. Then you can generate an API key and use it to post events.

It is an open question as to whether it is better to regenerate the calendar from scratch on each run of the script or to modify existing events.

**Comment by KristinaTaylor** [comment]
Idea: as a first step - is there a way to do a simple "add to my calendar" link per event, or does that clutter the page too much?

**Comment by pnijjar** [comment]
I wrote a script to do the updating. It needs to be run manually (and thus far only I have the credentials for the service account). My hope is to run this from a cronjob on a server soon.

This is fixed by #53
