### ISSUE TITLE
Load advance polling dates into events.csv

### ISSUE THREAD

**Issue by KristinaTaylor** [CivicTechWR/WRvotes#48]
Gather advance polling dates for area municipalities, and internet voting dates for North Dumfries and Cambridge, and load them into events.csv

**Comment by Selskiy** [comment]
Cambridge advance voting dates: 
October 3, 2018	
Between the hours of 4:00 p.m. and 8:00 p.m. at Cambridge City Hall (Bowman Room)
October 6, 2018	
Between the hours of 10:00 a.m. and 6:00 p.m. at the Hespeler Arena and Preston Auditorium, and between the hours of 9:00 a.m. and 5:00 p.m. at Cambridge City Hall (Bowman Room)
October 9, 2018
Online Voting Opens (at 10:00 a.m.)
October 10, 2018
Between the hours of 4:00 p.m. and 8:00 p.m. at the Cambridge City Hall (Bowman Room)
October 13, 2018
Between the hours of 10:00 a.m. and 6:00 p.m. at the Hespeler Arena and Preston Auditorium, and between the hours of 9:00 a.m. and 5:00 p.m. at Cambridge City Hall (Bowman Room)
October 22, 2018
Online Voting Closes (at 7:59 p.m.)
SOURCE: https://www.cambridge.ca/en/your-city/information-for-voters.aspx

**Comment by Selskiy** [comment]
Woolwich advance polling dates:
October 9, 2018, at 10:00 am to October 22, 2018, at 8:00 pm.
Source: https://www.woolwich.ca/en/township-services/information-for-voters.aspx

**Comment by Selskiy** [comment]
Waterloo advance polling dates:
Saturday, October 6	
Waterloo City Centre*  10 a.m. to 2 p.m.
Wednesday, October 10	
Waterloo City Centre*  10 a.m. to 6 p.m.
Wednesday, October 10	
RIM Park	12 p.m. to 8 p.m.
Thursday, October 11	
Waterloo Memorial Recreation Complex  12 p.m. to 8 p.m.
Saturday, October 13	
Waterloo Public Library John Harper Branch	12 p.m. to 8 p.m.

Source: https://www.waterloo.ca/en/government/where-when-to-vote.asp

**Comment by Selskiy** [comment]
Wellesley advanced voting:
Voting will commence on October 9, 2018 at 10:00 am through to October 22, 2018 at
8:00 pm.

Source: https://www.wellesley.ca/en/township-services/resources/Documents/Township-of-Wellesley-2018-Municipal-Election-Procedure-and-Forms.pdf (page 30)

**Comment by pnijjar** [comment]
North Dumfries: no dates listed?
https://www.northdumfries.ca/en/township-services/information-for-voters-.aspx

It looks like they are doing Internet voting and telephone voting only. I don't know the dates.

**Comment by pnijjar** [comment]
Wilmot: October 6 and October 10. 

> Advance Polls will be on October 6 at the WRC and October 10 at the Township  
> Administrative Complex.  We are not using internet or telephone voting.  We   
> are using paper ballots with vote count tabulators.  

I believe the administrative complex is: 60 Snyder’s Road West, Baden, ON

For North Dumfries: 

> The Township of North Dumfries will be voting by internet and telephone only  for the October 22 Municipal Election. The voting period is from October 9 -  22, 2018.

**Comment by pnijjar** [comment]
I added these to the events.csv . Thanks.
