### ISSUE TITLE
Generally test website on mobile

### ISSUE THREAD

**Issue by KristinaTaylor** [CivicTechWR/WRvotes#49]

**Comment by jeffwoods** [comment]
I tried.  It's not the best.

**Comment by pnijjar** [comment]
I know about the issue where the website appears only on the left half of the screen. What else is broken?

**Comment by KristinaTaylor** [comment]
I think things are good now. I tried several pages with the new design a few different devices I have access to at work. Also google search console says the site is mobile friendly, and if you can't trust google, who can you trust? 😉
