### ISSUE TITLE
Test/fix social media sharing

### ISSUE THREAD

**Issue by KristinaTaylor** [CivicTechWR/WRvotes#50]

**Comment by pnijjar** [comment]
I tested LinkedIn and it appeared to work? I was not logged in, I clicked the link, it prompted me to log in and then it shared the link. It did not let me put extra text, but it did share on my wall.

**Comment by KristinaTaylor** [comment]
Yes, this is resolved - I can tell that people have been using it on Twitter for sure, because they're using my hashtags. Facebook works if you have platform enabled, and LinkedIn is working too. I just can't track those because they don't auto-tag us.
