### ISSUE TITLE
Clarify how people vote and get on the voter's list

### ISSUE THREAD

**Issue by pnijjar** [CivicTechWR/WRvotes#55]
Some area municipalities do Internet voting only! Some do regular voting only! Cambridge does both!

It is not clear what the rules are for eligibility in the different municpalities. We need to figure this out and document this.

**Comment by pnijjar** [comment]
Related questions: 

- What is the last day people can register for the voter's list in each municipality?
- How do people register for the voter's list?
- Does voterlookup.ca stop working at the end of August?
- When people register to vote, what does the school board designation mean?

**Comment by KristinaTaylor** [comment]
**Waterloo**
Confirm/Add via https://www.waterloo.ca/en/government/voter-registration.asp
or contact: 
City of Waterloo
100 Regina St. S.
PO Box 337, Station Waterloo
Waterloo, Ont.
N2J 4A8

elections@waterloo.ca
519-747-8704
TTY. 1-866-786-3941


**Kitchener:**
voterlookup.ca
"If your name is on the Voters' List, you will receive a Voter Notification Card (VNC) by mail. This card provides you with information on where and when you can vote. Bring this card with you to the poll, to speed up the time it takes you to vote."
"You can also fill out an application to amend the Voters' List and submit to Legislated Services on the second floor at city hall, 200 King St. W, Kitchener from September 4th-October 19th. Applications will also be available on Election Day at your voting location – please allow extra time if you choose to correct/add to the Voters’ List on Election Day. "
Form: https://lf.kitchener.ca/WebLinkExt/DocView.aspx?dbid=0&id=1705934&_ga=2.53806632.1802388269.1535916888-2068458943.1532310666

**Comment by KristinaTaylor** [comment]
**Cambridge:**
If you're not showing up on voterlookup.ca or you want to change something, take this complete form https://www.cambridge.ca/en/resources/Form-EL15---Application-to-Amend-Voters-List-Fillable.pdf to the Clerk's Division (50 Dickson Street, 2nd Floor, Cambridge, ON). 
Online, Advance, in-person on election day are all available. Find your polling place here if you didn't get the card: https://cityofcambridge.maps.arcgis.com/apps/InformationLookup/index.html?appid=5b26f2e0b29d4bdf92fcf76eb61efd13
Contact:
Clerks Information
election2018@cambridge.ca 
50 Dickson Street, 1st floor, Cambridge ON N1R 8S1
T. (519) 623-1340
TTY (519) 623-6691
F. (519) 740-4637

**Comment by KristinaTaylor** [comment]
The remaining task here is to figure out how to coherently organize all of the information above into the right sections of this page, particularly this section: https://waterlooregionvotes.org/resources/voter-info#how-do-i-register-to-vote

**Comment by pnijjar** [comment]
Good work on researching this. I do not think that integrating this information will be too hard.
