### ISSUE TITLE
Make it easy to link directly to the map

### ISSUE THREAD

**Issue by acant** [CivicTechWR/WRvotes#80]
I posted a link to the site in reply to a KitchenerPost article with a terrible map.
* https://twitter.com/KitchenerPost/status/1042498545767657472
* https://www.kitchenerpost.ca/news-story/8909946-municipal-election-2018-kitchener-council-candidates-respond/#.W6KlwhG7DrY.twitter

And I noticed that someone clicking on the link would need to scroll down in order to see the map. I think that we should make it easier to link directly to the map. Some options:
1. add an anchor tag into the front page, so that we can link to the map section directly
2. create a seperate full screen map page

1 is easy, so I can do that first. 

Are there any opinions on 2? I imagine something list the default OSM view with the wards and address search included.
https://www.openstreetmap.org/#map=12/43.4372/-80.5215

**Comment by pnijjar** [comment]
How about we just get rid of a bunch of text on the front page?

It looks like the following URLs work already: 

https://waterlooregionvotes.org/#map
https://waterlooregionvotes.org/#map-searchbar

I also added

https://waterlooregionvotes.org/#search

**Comment by acant** [comment]
Thank you @pnijjar!
